from database import execute_query


def list_tables():
    query = "SHOW TABLES;"
    result = execute_query(query)
    return [list(row.values())[0] for row in result]


def get_table_schema(table_name):
    query = f"DESCRIBE {table_name};"
    return execute_query(query)


def run_sql(query):
    """
    Execute read-only SQL generated by the SQL agent.
    This backend check is the real SQL safety layer.
    """
    if not query:
        return {"error": "Empty SQL query."}

    query_clean = query.strip()

    # Allow one trailing semicolon only
    if query_clean.endswith(";"):
        query_clean = query_clean[:-1].strip()

    # Block multiple statements
    if ";" in query_clean:
        return {
            "error": "Blocked unsafe SQL operation. Multiple SQL statements are not allowed."
        }

    query_lower = query_clean.lower()

    # Allow read-only operations only
    allowed_prefixes = ("select", "with", "show", "describe", "desc", "explain")
    if not query_lower.startswith(allowed_prefixes):
        return {
            "error": "Blocked unsafe SQL operation. Only read-only SQL queries are allowed."
        }

    blocked_keywords = [
        "insert",
        "update",
        "delete",
        "drop",
        "truncate",
        "alter",
        "create",
        "replace",
        "grant",
        "revoke",
    ]

    # Extra protection against destructive keywords inside the query
    for word in blocked_keywords:
        if f" {word} " in f" {query_lower} ":
            return {
                "error": "Blocked unsafe SQL operation. Only read-only SQL queries are allowed."
            }

    return execute_query(query_clean)